sudo: required
dist: trusty
language: bash

# Handle git submodules yourself (see http://stackoverflow.com/questions/15674064/)
git:
  submodules: false

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -qq emacs24 jing xmlstarlet libxml2-utils parallel libxml2 fonts-tibetan-machine fonts-texgyre ttf-indic-fonts realpath libsaxonb-java time poppler-utils python-pygments libwww-perl
  # install tex, see https://github.com/scottkosty/install-tl-ubuntu/
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  # - wget http://ctan.mirror.rafal.ca/systems/texlive/Images/texlive.iso
  - pwd
  - ls
  - sudo ./install-tl-ubuntu -profile ./paddymcall/SARIT-pdf-conversions/.texlive.profile
  - sudo tlmgr install `cat ./paddymcall/SARIT-pdf-conversions/.texlive.packages`
  # - cat /etc/environment

script:
  - for i in `find ./TeX/ -type f -iname "*.tex"  -printf '%f\n' |  sed 's/tex$/xml/'`; do echo "./bin/convert_sarit_to_tex.sh \"./SARIT-corpus/$i\""; done > /tmp/conv.txt
  - parallel < /tmp/conv.txt > /dev/null 2>&1
  - cd ./TeX
  # - sed -i '0,/%%\\syntaxonly/{s/%%\\syntaxonly/\\syntaxonly/}' ./*tex
  - for i in `ls *tex`; do echo "xelatex -interaction=batchmode -8bit -shell-escape \"$i\""; done > /tmp/tex.txt
  - for i in `ls *tex`; do echo "biber \"`basename $i .tex`\""; done > /tmp/bib.txt
  - parallel < /tmp/tex.txt >> general.log 2>&1
  - parallel < /tmp/bib.txt >> general.log 2>&1
  - parallel < /tmp/tex.txt >> general.log 2>&1
  - parallel < /tmp/bib.txt >> general.log 2>&1
  - parallel < /tmp/tex.txt >> general.log 2>&1

after_script:
  # - echo "PDF stats:"
  # - for i in `ls ./*pdf`; do echo "==== For $i"; pdfinfo "$i"; done
  - echo "Last 40 lines of log files:"
  - tail -n 40 ./*log
  - echo "Erorrs in log files (if > 2 problematic):"
  - rgrep -c -i error ./*log


  
