sudo: required
dist: trusty
language: bash

# Handle git submodules yourself (see http://stackoverflow.com/questions/15674064/)
git:
  submodules: false

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y emacs24 jing xmlstarlet libxml2-utils parallel libxml2 fonts-tibetan-machine fonts-texgyre ttf-indic-fonts realpath libsaxonb-java time poppler-utils python-pygments libwww-perl latexmk
  # install tex, see https://github.com/scottkosty/install-tl-ubuntu/
  # - wget https://github.com/paddymcall/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  # - wget http://ctan.mirror.rafal.ca/systems/texlive/Images/texlive.iso
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar zxf install-tl-unx.tar.gz
  - cd ./install-tl-*
  - ./install-tl -profile ../.texlive.profile
  - tlmgr install `cat ../.texlive.packages`
  - cd ..
  - mkdir ~/test-build
  # - cat /etc/environment

script:
  - travis_wait 59 ./bin/build_all.sh SARIT-corpus/saritcorpus.xml ~/test-build

after_script:
  # - echo "PDF stats:"
  # - for i in `ls ./*pdf`; do echo "==== For $i"; pdfinfo "$i"; done
  - echo "Last 40 lines of log files:"
  - tail -n 40 ~/test-build/*log
  - echo "Erorrs in log files (if > 2 problematic):"
  - rgrep -c -i error ~/test-build/*log
  - echo "Erorrs in log files with context:"
  - rgrep -C 4 -i error ~/test-build/*log


  
