sudo: required
dist: trusty
language: bash

# Handle git submodules yourself (see http://stackoverflow.com/questions/15674064/)
git:
  submodules: false

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -qq emacs24 jing xmlstarlet libxml2-utils parallel libxml2 fonts-tibetan-machine fonts-texgyre ttf-indic-fonts realpath libsaxonb-java time poppler-utils python-pygments libwww-perl
  # install tex, see https://github.com/scottkosty/install-tl-ubuntu/
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  # - cat /etc/environment

script:
  - xmlstarlet sel -N xi="http://www.w3.org/2001/XInclude" -t -m "//xi:include/@href" -o "./bin/convert_sarit_to_tex.sh " -o "SARIT-corpus/" -v "." -n  "./SARIT-corpus/saritcorpus.xml" > /tmp/conv.txt
  - parallel < /tmp/conv.txt > /dev/null 2>&1
  - cd ./TeX
  - sed -i '0,/%%\\syntaxonly/{s/%%\\syntaxonly/\\syntaxonly/}' ./*tex
  - echo "Checking TeX syntax"
  - for i in `ls *tex`; do echo "echo Compiling \"$i\" && xelatex -no-pdf -shell-escape -8bit -interaction=batchmode \"$i\""; done > /tmp/tex.txt
  - parallel < /tmp/tex.txt  >> general.log
  - for i in `ls *tex`; do  echo "bibtex \""`basename $i .tex`"\""; done > /tmp/bibtex.txt
  - echo "Bibtex ..."
  - parallel < /tmp/bibtex.txt  >> general.log
  - echo "Second latex run ..."
  - parallel < /tmp/tex.txt  >> general.log

after_script:
  # - echo "PDF stats:"
  # - for i in `ls ./*pdf`; do echo "==== For $i"; pdfinfo "$i"; done
  - echo "Last 40 lines of log files:"
  - tail -n 40 ./*log
  - echo "Erorrs in log files (if > 2 problematic):"
  - rgrep -c -i error ./*log


  
