sudo: required
dist: trusty
language: bash

# Handle git submodules yourself (see http://stackoverflow.com/questions/15674064/)
git:
  submodules: false

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -qq emacs24 jing xmlstarlet libxml2-utils parallel libxml2 fonts-tibetan-machine fonts-texgyre ttf-indic-fonts realpath libsaxonb-java
  # install tex, see https://github.com/scottkosty/install-tl-ubuntu/
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  # - cat /etc/environment

script:
  - for i in `xmlstarlet sel -N xi='http://www.w3.org/2001/XInclude' -t -v '//xi:include/@href'  ./SARIT-corpus/saritcorpus.xml`; do ./bin/convert_sarit_to_tex.sh ./SARIT-corpus/"$i"; done > travislog.txt 2>&1
  - cd ./TeX
  - echo "Compiling TeX"
  - for i in `ls *tex`; do xelatex -shell-escape -8bit -interaction=nonstopmode "$i" >> travislog.txt 2>&1 ; done
  - for i in `ls *tex`; do biber `basename "$i" tex` >> travislog.txt 2>&1 ; done
  - for i in `ls *tex`; do xelatex -shell-escape -8bit -interaction=nonstopmode "$i" >> travislog.txt 2>&1 ; done
  - for i in `ls *tex`; do biber `basename "$i" tex` >> travislog.txt 2>&1 ; done
  - for i in `ls *tex`; do xelatex -shell-escape -8bit -interaction=nonstopmode "$i" >> travislog.txt 2>&1 ; done
  - tail -n 100 travislog.txt
